rappmanager:
  csarlocation: src/test/resources/csar
  acm:
    baseurl: http://localhost:55562/onap/policy/clamp/acm/v2/
    username: runtimeUser
    password: changeme
    maxRetries: 10
    retryInterval: 2
  sme:
    baseurl: http://localhost:8095
    providerBasePath: /api-provider-management/v1/
    invokerBasePath: /api-invoker-management/v1/
    publishApiBasePath: /published-apis/v1/
    maxRetries: 3
    retryInterval: 2
  dme:
    baseurl: http://localhost:9082
    telemetry:
      enabled: true
      database-path: ../rapp-manager-models/data/ran_telemetry.db
      api-base-path: /dme/ran-telemetry/v1
  rapps:
    env:
      smeDiscoveryEndpoint: http://localhost:8095/service-apis/v1/allServiceAPIs

server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    root: INFO
    org.oransc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
